### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-yase-collector-surgeon#3]
I do have a flag for resume which works such that if a node exists with the name of the url, it skips it.

Resuming should probably be re-thought in term of a queue of some sort.

**Comment by sigdestad** [comment]
It might not be safe to use url as name, names are limited to 255 chars.

**Comment by ComLock** [comment]
@sigdestad Oh, is that documented anywhere? What about lib-cache keys, are they also limited.

I guess I will have to use some kind of fast one way hash algorithm with low collision.

I typically use fnv1a.

https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed

But that does not give any guarantees. So perhaps a lookup table would be better.

**Comment by ComLock** [comment]
1024 bit fnv-plus str should be good enough. 

```javascript
const hash = require('fnv-plus').hash;

[
	'https://www.example.com',
	'https://www.example.com/lkdjfhgladkghjlaidrughoi3u4yt2oiuty2oeirjgnlakdfjnoqeiuht20oieruhgqlkdsfjgbqo3i4ughldafjkbgqo35iug'
].forEach(uri => {
	[/*32, 52, 64, 128, 256, 512, */1024].forEach(bit => {
		const a = hash(uri, bit)
		console.log(uri);
		//console.log(a.dec());
		//console.log(a.dec().length); // Not static length
		console.log(a.hex());
		console.log(a.hex().length);
		console.log(a.str());
		console.log(a.str().length);
	})
})
```

**Comment by ComLock** [comment]
I think the current resume is good enough
